"""complete schema rebuild

Revision ID: 006d8ff077ed
Revises: 802fcbcde787
Create Date: 2026-04-21 09:31:32.426455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '006d8ff077ed'
down_revision: Union[str, Sequence[str], None] = '802fcbcde787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('course_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('ta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['ta_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_assignments_id'), 'course_assignments', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('student_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'graded', 'reviewed', name='submissionstatus'), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_submissions_id'), 'student_submissions', ['id'], unique=False)
    op.create_table('answer_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['student_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_extractions_id'), 'answer_extractions', ['id'], unique=False)
    op.create_table('plagiarism_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('submission_1_id', sa.Integer(), nullable=True),
    sa.Column('submission_2_id', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['submission_1_id'], ['student_submissions.id'], ),
    sa.ForeignKeyConstraint(['submission_2_id'], ['student_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plagiarism_flags_id'), 'plagiarism_flags', ['id'], unique=False)
    op.create_table('rubric_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('condition_text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubric_conditions_id'), 'rubric_conditions', ['id'], unique=False)
    op.create_table('ai_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_urgent_review', sa.Boolean(), nullable=True),
    sa.Column('condition_breakdown', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['answer_extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_grades_id'), 'ai_grades', ['id'], unique=False)
    op.create_table('final_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_grade_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('ta_comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_grade_id'], ['ai_grades.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_grades_id'), 'final_grades', ['id'], unique=False)
    op.add_column('exams', sa.Column('title', sa.String(), nullable=False))
    op.add_column('exams', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('exams', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('exams', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('exams_uploaded_by_fkey'), 'exams', type_='foreignkey')
    op.create_foreign_key(None, 'exams', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'exams', 'courses', ['course_id'], ['id'])
    op.drop_column('exams', 'uploaded_at')
    op.drop_column('exams', 'student_name')
    op.drop_column('exams', 'course')
    op.drop_column('exams', 'status')
    op.drop_column('exams', 'file_path')
    op.drop_column('exams', 'student_id')
    op.drop_column('exams', 'uploaded_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('status', postgresql.ENUM('uploaded', 'processing', 'graded', 'reviewed', name='examstatus'), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('student_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.create_foreign_key(op.f('exams_uploaded_by_fkey'), 'exams', 'users', ['uploaded_by'], ['id'])
    op.drop_column('exams', 'created_at')
    op.drop_column('exams', 'created_by')
    op.drop_column('exams', 'course_id')
    op.drop_column('exams', 'title')
    op.drop_index(op.f('ix_final_grades_id'), table_name='final_grades')
    op.drop_table('final_grades')
    op.drop_index(op.f('ix_ai_grades_id'), table_name='ai_grades')
    op.drop_table('ai_grades')
    op.drop_index(op.f('ix_rubric_conditions_id'), table_name='rubric_conditions')
    op.drop_table('rubric_conditions')
    op.drop_index(op.f('ix_plagiarism_flags_id'), table_name='plagiarism_flags')
    op.drop_table('plagiarism_flags')
    op.drop_index(op.f('ix_answer_extractions_id'), table_name='answer_extractions')
    op.drop_table('answer_extractions')
    op.drop_index(op.f('ix_student_submissions_id'), table_name='student_submissions')
    op.drop_table('student_submissions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_course_assignments_id'), table_name='course_assignments')
    op.drop_table('course_assignments')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
